# Generated by Django 4.0.4 on 2022-05-22 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, default='header', help_text='<small class="text-muted">это наш заголовок</small><hr><br>', max_length=254, null=True, verbose_name='description')),
                ('description', models.TextField(null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
        ),
    ]
