# Generated by Django 4.0.4 on 2022-05-22 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_second', '0006_remove_task_user_user_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_second.user'),
        ),
    ]
